### ISSUE TITLE
status of the project

### ISSUE THREAD

**Issue by mheiber** [steos/myro#3]
I really like the idea of separating route matching from routing, the API here is beautiful, and it's great that routes can be nested.

Would you recommend using this library?

**Comment by wagerfield** [comment]
I too would like to know if this project is still alive? Learnt of it from this great article on [Functional Front-Ends with Inferno](https://medium.com/javascript-inside/introduction-to-functional-front-ends-with-inferno-side-effects-and-routing-a8b226c47b0f#.n3gy7bgfq)

**Comment by steos** [comment]
Yes it is definitely alive, I use it myself.

**Comment by wagerfield** [comment]
That's great to hear—I too am very much a fan of it's design. I assume by the lack of issues and commits that it simply just works and hasn't needed any updates :)

**Comment by mheiber** [comment]
Nice work! Looking forward to using this.

**Comment by steos** [comment]
Thanks for the nice words. It works well enough for me, but lack of issues is probably more due to a lack of users :) 
If you have any issues using it or suggestions for improvements etc. I'll appreciate any feedback.
